name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Download a file tf_model.h5
        run: wget https://huggingface.co/bert-base-cased/blob/main/tf_model.h5 -O bert/tf_model.h5
      - name: Download a file pytorch_model.bin 
        run: wget https://huggingface.co/bert-base-cased/resolve/main/pytorch_model.bin -O bert/pytorch_model.bin 
      - uses: actions/upload-artifact@v3
        with:
          name: bert-artifact
          path: bert/